version: '3'
services:

  mariadb:
    image: mariadb:10.3
    container_name: go-timisoara-mysql-server
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Bucharest"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'go_root'
      MYSQL_USER: 'go_user'
      MYSQL_PASSWORD: 'go_password'
      MYSQL_DATABASE: 'go'
    ports:
      - 3306:3306

volumes:
  mariadb: